### ISSUE TITLE
I have found several sanic template libraries, only you can use them, thank you!

### ISSUE THREAD

**Issue by jiayouzl** [tuna2134/sanic-template#1]
I have found several sanic template libraries, only you can use them, thank you!

**Comment by tuna2134** [comment]
Well, sanic-ext has template system so I think you could use sanic-ext

**Comment by tuna2134** [comment]
And This library need rewrite.

**Comment by jiayouzl** [comment]
> 



> Well, sanic-ext has template system so I think you could use sanic-ext

sanic-ext Is there a document website?

**Comment by tuna2134** [comment]
https://sanic.dev/en/plugins/sanic-ext/templating.html#dependencies

**Comment by jiayouzl** [comment]
> https://sanic.dev/en/plugins/sanic-ext/templating.html#dependencies

Thank you very much!
